version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - RAILS_ENV=development
    command: bash -c "bundle install && rails db:migrate && rails server -b 0.0.0.0"
