services:
  web:
    image: ruby:3.0.2
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    command: >
      bash -c "
        apt-get update -qq &&
        apt-get install -y nodejs sqlite3 libsqlite3-dev &&
        bundle install &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails server -b 0.0.0.0
      "
